server:
  port: 8085
spring:
  application:
    name: ha-file
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

alioss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: accessKeyId
  accessKeySecret: accessKeySecret
  bucketName: testbucket
  urlPrefix: http://testbucket.oss-cn-shanghai.aliyuncs.com/


eureka:
  client:
    service-url:
      defaultZone: http://weirdo:weirdo@127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms