server:
  port: 8087
spring:
  application:
    name: ha-search
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
  rabbitmq:
    virtual-host: /ha
    username: /ha
    password: ha
    host: 192.168.19.121
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  resources:
    add-mappings: true
    chain:
      enabled: true
      gzipped: true
      html-application-cache: true
    cache:
      period: 3600m
eureka:
  client:
    service-url:
      defaultZone: http://weirdo:weirdo@127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳